<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MomentFerry.Core\MomentFerry.Core.csproj" />
    <ProjectReference Include="..\MomentFerry.Application\MomentFerry.Application.csproj" />
    <ProjectReference Include="..\MomentFerry.Infrastructure\MomentFerry.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.2" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>
</Project>
